#cloud-config
hostname: ${hostname}
create_hostname_file: true
fqdn: ${fqdn}
package_update: true
packages:
  - qemu-guest-agent
  - apt
  - mc
  - net-tools
  - bind-utils
users:
  - name: root
    shell: /bin/bash
    ssh_authorized_keys:
      - ${keyroot}
  - name: ${users}
    groups: sudo
    home: /home/${users}
    shell: /bin/bash
    lock_passwd: false
    passwd: ${secret}
    ssh_authorized_keys:
      - ${keyuser}
ssh_pwauth: true
write_files:
  - path: /opt/install-docker.sh
    permissions: "0700"    
    content: |
      #!/bin/bash
      apt-get update
      apt-get install ca-certificates curl -y
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y 
runcmd:
  - systemctl enable --now qemu-guest-agent
  - bash /opt/./install-docker.sh
  - rm -rf /opt/*
 

final_message: "The system is finally up, after $UPTIME seconds" 
